apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.full.yml convert
    kompose.version: 1.8.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: armory-utxsvr-testnet
  name: armory-utxsvr-testnet
spec:
  clusterIP: None
  ports:
  - name: headless
    port: 55555
    targetPort: 0
  selector:
    io.kompose.service: armory-utxsvr-testnet
status:
  loadBalancer: {}
