apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.full.yml convert
    kompose.version: 1.8.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: bitcoin-testnet
  name: bitcoin-testnet
spec:
  ports:
  - name: "18332"
    port: 18332
    targetPort: 18332
  selector:
    io.kompose.service: bitcoin-testnet
status:
  loadBalancer: {}
