apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.full.yml convert
    kompose.version: 1.8.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: bitcoin
  name: bitcoin
spec:
  ports:
  - name: "8332"
    port: 8332
    targetPort: 8332
  selector:
    io.kompose.service: bitcoin
status:
  loadBalancer: {}
