apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.full.yml convert
    kompose.version: 1.8.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: bitcoin-testnet
  name: bitcoin-testnet
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: bitcoin-testnet
    spec:
      containers:
      - env:
        - name: PARAMS
          value: -conf=/root/.bitcoin-config/bitcoin.testnet.conf
        image: counterparty/bitcoin:latest
        name: bitcoin-testnet
        ports:
        - containerPort: 18332
        resources: {}
        volumeMounts:
        - mountPath: /root/.bitcoin-config
          name: bitcoin-testnet-claim0
        - mountPath: /root/.bitcoin/
          name: bitcoin-data
      restartPolicy: Always
      volumes:
      - name: bitcoin-testnet-claim0
        persistentVolumeClaim:
          claimName: bitcoin-testnet-claim0
      - name: bitcoin-data
        persistentVolumeClaim:
          claimName: bitcoin-data
status: {}
