apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.full.yml convert
    kompose.version: 1.8.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: counterwallet
  name: counterwallet
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: counterwallet
    spec:
      containers:
      - image: counterparty/counterwallet:latest
        name: counterwallet
        ports:
        - containerPort: 80
        - containerPort: 443
        resources: {}
        volumeMounts:
        - mountPath: /counterwallet
          name: counterwallet-claim0
        - mountPath: /ssl-config
          name: counterwallet-claim1
        - mountPath: /counterblock-data
          name: counterblock-data
      restartPolicy: Always
      volumes:
      - name: counterwallet-claim0
        persistentVolumeClaim:
          claimName: counterwallet-claim0
      - name: counterwallet-claim1
        persistentVolumeClaim:
          claimName: counterwallet-claim1
      - name: counterblock-data
        persistentVolumeClaim:
          claimName: counterblock-data
status: {}
