apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.full.yml convert
    kompose.version: 1.8.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: counterblock-testnet
  name: counterblock-testnet
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: counterblock-testnet
    spec:
      containers:
      - env:
        - name: PARAMS
          value: --config-file=/root/.config/counterblock/server.testnet.conf
        image: counterparty/counterblock:latest
        name: counterblock-testnet
        ports:
        - containerPort: 14100
        - containerPort: 14101
        - containerPort: 14102
        resources: {}
        volumeMounts:
        - mountPath: /counterblock
          name: counterblock-testnet-claim0
        - mountPath: /root/.config/counterblock
          name: counterblock-testnet-claim1
        - mountPath: /root/.local/share/counterblock
          name: counterblock-data
      restartPolicy: Always
      volumes:
      - name: counterblock-testnet-claim0
        persistentVolumeClaim:
          claimName: counterblock-testnet-claim0
      - name: counterblock-testnet-claim1
        persistentVolumeClaim:
          claimName: counterblock-testnet-claim1
      - name: counterblock-data
        persistentVolumeClaim:
          claimName: counterblock-data
status: {}
