apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.full.yml convert
    kompose.version: 1.8.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: counterparty-testnet
  name: counterparty-testnet
spec:
  ports:
  - name: "14000"
    port: 14000
    targetPort: 14000
  selector:
    io.kompose.service: counterparty-testnet
status:
  loadBalancer: {}
